### ISSUE TITLE
Dijkstra algorithm for shortest path in weighted graph

### ISSUE THREAD

**Issue by TheDesTrucToRR** [Idhant-6/Hacktoberfest-2021#41]
A python program to find shortest path between two vertices in a weighted graph.

**Comment by TheDesTrucToRR** [comment]
@Idhant-6 please assign this issue to me. I would like to work on it.

**Comment by Idhant-6** [comment]
Really?

**Comment by Idhant-6** [comment]
Yes it is!

**Comment by TheDesTrucToRR** [comment]
Yes then I would really like to work on it.

**Comment by TheDesTrucToRR** [comment]
@Idhant-6 Thanks. I would like to add some more contributions of Python program.
